name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2  # Specify your AWS region here

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1
        with:
          registry-type: public
          region: us-west-1  # Specify your AWS region here

      - name: Build Docker Image
        run: |
          docker build -t my-image:${{ github.sha }} .
          docker tag my-image:${{ github.sha }} <aws_account_id>.dkr.ecr.us-west-2.amazonaws.com/my-repo:latest

      - name: Push Docker Image to ECR
        run: |
          docker push <aws_account_id>.dkr.ecr.us-west-2.amazonaws.com/my-repo:latest
